### ISSUE TITLE
Wallet is not syncing

### ISSUE THREAD

**Issue by BraamSteyn7777** [coinonat/CoinonatX#10]
Hi
Wallet is not syncing. Impossible to do anything. Running under Windows 10
Running V2.0.2.2: MN-Swap-Ready
Wallet not responsive, very slow each time it is clicked
![image](https://user-images.githubusercontent.com/34418434/33805674-6834a392-ddc5-11e7-9481-4ece93020340.png)

**Comment by crowimu** [comment]
same here, very unresponsive

**Comment by FreeZoneAT** [comment]
Very very unresponsive, like every click..

Please update the Wallet..

**Comment by unsub23** [comment]
*UPDATE - For people with this issue - Turned out to be local office firewall related. Try syncing from a different location. Fixed it for me.

Original Issue:
Same issue still. shows connected to zero nodes.

**Comment by coinonat** [comment]
In the update v2.0.4.4 we will fix this problem.

**Comment by deflabs** [comment]
@coinonat  Where is the Windows wallet download for version 2.0.4.4?
