### ISSUE TITLE
Linux build not working

### ISSUE THREAD

**Issue by FreeZoneAT** [coinonat/CoinonatX#11]
/CoinonatX/src# make -f makefile.unix
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/lukas/masternode/CoinonatX/src -I/home/lukas/masternode/CoinonatX/src/obj -DENABLE_WALLET -I/home/lukas/masternode/CoinonatX/src/leveldb/include -I/home/lukas/masternode/CoinonatX/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
In file included from alert.h:9:0,
                 from alert.cpp:5:
serialize.h:19:48: fatal error: boost/type_traits/is_fundamental.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
makefile.unix:217: die Regel für Ziel „obj/alert.o“ scheiterte
make: *** [obj/alert.o] Fehler 1

**Comment by coinonat** [comment]
Please install all build software: sudo apt-get install libssl-dev openssl git miniupnpc libdb-dev libdb++-dev build-essential libgmp-dev autoconf libtool libboost-all-dev libcurl4-openssl-dev git libboost-chrono-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev libprotobuf-dev protobuf-compiler libqrencode-dev -y
