### ISSUE TITLE
Compile error at obj/rpcclient.o phase

### ISSUE THREAD

**Issue by tucksmcgucks** [coinonat/CoinonatX#3]
I get an error when compiling during the 'obj/rpcclient.o' phase: 
'make: *** [obj/rpcclient.o] Error 1'

Seems to be an issue with the function call_once:

```
/usr/include/boost/thread/once.hpp:38:18: error: no matching function for call to ‘call_once(boost::once_flag&, void (*&)())’
         call_once(flag,func);
                  ^
```

Here where the compile errors out:

`rpcclient.cpp:88:40:   required from here
/usr/include/boost/thread/once.hpp:38:18: error: no matching function for call to ‘call_once(boost::once_flag&, void (*&)())’
         call_once(flag,func);
                  ^
In file included from /usr/include/boost/thread/once.hpp:20:0,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/object_with_id.ipp:18,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp:15,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/grammar.hpp:21,
                 from /usr/include/boost/spirit/home/classic/core.hpp:42,
                 from /usr/include/boost/spirit/include/classic_core.hpp:11,
                 from json/json_spirit_reader_template.h:19,
                 from rpcclient.h:9,
                 from rpcclient.cpp:7:
/usr/include/boost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void boost::call_once(boost::once_flag&, boost::detail::thread_move_t<T>, boost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
/usr/include/boost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
In file included from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/object_with_id.ipp:18:0,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/impl/grammar.ipp:15,
                 from /usr/include/boost/spirit/home/classic/core/non_terminal/grammar.hpp:21,
                 from /usr/include/boost/spirit/home/classic/core.hpp:42,
                 from /usr/include/boost/spirit/include/classic_core.hpp:11,
                 from json/json_spirit_reader_template.h:19,
                 from rpcclient.h:9,
                 from rpcclient.cpp:7:
/usr/include/boost/thread/once.hpp:38:18: note:   mismatched types ‘boost::detail::thread_move_t<T>’ and ‘void (*)()’
         call_once(flag,func);
                  ^
/usr/include/boost/thread/once.hpp:35:13: note: candidate: template<class Function> void boost::call_once(Function, boost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
/usr/include/boost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
/usr/include/boost/thread/once.hpp:38:18: note:   cannot convert ‘func’ (type ‘void (*)()’) to type ‘boost::once_flag&’
         call_once(flag,func);
                  ^
make: *** [obj/rpcclient.o] Error 1
`

**Comment by coinonat** [comment]
Please install all build software: sudo apt-get install libssl-dev openssl git miniupnpc libdb-dev libdb++-dev build-essential libgmp-dev autoconf libtool libboost-all-dev libcurl4-openssl-dev git libboost-chrono-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libboost-thread-dev libprotobuf-dev protobuf-compiler libqrencode-dev -y
